locales/en.yml
I went through the English translations and corrected a few grammar mistakes. I also rewrote a few sentences that I thought were a bit unclear.
=> Update English translations

source/javascripts/all.js, source/layouts/layout.erb
=> migrate CRM

README.md
=> clarify automagicly acces of weblate

source/layouts/layout.erb, source/stylesheets/main.css.scss
Preconnect to google fonts and load stylesheet in parallel.
=> Optimize font loading

locales/de.yml, node-deps.sh, package.json, source/partials/_offer2.erb
https://github.com/appuio/price-calculator/compare/970c708996bec32d42a2c5cd407c051cbe10de92...a432a4498702dbb9dbfba8677d0b2ebdb871ef98
=> Use new slider data

price-calc.sh, source/partials/_offer2.erb
https://github.com/appuio/price-calculator/commit/7d9b6df94fe177be8086be56e897e7a05258b0ee
=> Update price calc to 3.0.0

source/layouts/layout.erb
update the link and site-id for visitor statistics because of new instance
=> change links for statistics

source/layouts/layout.erb
Change the image link for stats to new matomo instance
=> update image statistics link

locales/de.yml
add Basel to title and removed September techlab
=> techlab update

locales/de.yml
removed old dates in bern and added basel into header
=> updated de techlabs

locales/en.yml
removed old dates and changed headers
=> updated en techlab

locales/de.yml, locales/en.yml
Removed the "Road map" part, removed a duplicated key
=> Removed Roadmap, removed a key duplicate

locales/de.yml, locales/en.yml, source/images/managed/automatisierung.svg, source/images/managed/devOps.svg, source/images/managed/entwickeln.svg, source/images/managed/freie_wahl.svg, source/images/managed/knowHow_sharing.svg, source/images/managed/sofortige_umsetzung.svg, source/partials/_offer1.erb, source/stylesheets/layout/_offer-managed.scss, source/stylesheets/main.css.scss
Added six new Advantages to the offer "Managed".
=> Advantages managed

locales/en.yml
Remove duplicated keys, update values
=> Remove duplicated keys, update key values

source/localizable/team.html.erb, source/stylesheets/layout/_team.scss
Add team photo to team page, remove orang border.
=> Add team photo to team page, remove orange border

source/localizable/partner.html.erb, source/partials/_nav.erb, source/partials/_offer1.erb, source/partials/_offer2.erb, source/partials/_offer3.erb
Hide the carousels for customers and partners
=> Hide Customer and partner

source/localizable/techlabs.html.erb, source/partials/_nav.erb, source/partials/_offer1.erb, source/partials/_offer3.erb
=> Fix path to images

locales/en.yml
The address has not been updated in the English version of the website.
=> Fix address of techlab Zurich

locales/de.yml, locales/en.yml
Remove AMM lab 21.10.2020 link
=> remove hold amm lab

locales/de.yml, locales/en.yml
=> remove booked up amm date

themes/appuio/static/admin/config.yml
=> Added widget for event tags

content/blog/2022-07-19-ruckblick-auf-6-jahre-appuio/index.en.md
Translation of the 6-year anniversary blog post in English
=> Translated article to English

themes/appuio/layouts/_default/_markup/render-image.html, themes/appuio/layouts/_default/_markup/render-link.html, themes/appuio/layouts/shortcodes/button.html
url and image rendering bug on techlab/acend will be fixed by correct markdown render hooks
=> Fix rendering
